<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'UthandoNews\Module'                => __DIR__ . '/Module.php',
  'UthandoNews\Controller\News'       => __DIR__ . '/src/UthandoNews/Controller/News.php',
  'UthandoNews\Event\ServiceListener' => __DIR__ . '/src/UthandoNews/Event/ServiceListener.php',
  'UthandoNews\Form\News'             => __DIR__ . '/src/UthandoNews/Form/News.php',
  'UthandoNews\Hydrator\News'         => __DIR__ . '/src/UthandoNews/Hydrator/News.php',
  'UthandoNews\InputFilter\News'      => __DIR__ . '/src/UthandoNews/InputFilter/News.php',
  'UthandoNews\Mapper\News'           => __DIR__ . '/src/UthandoNews/Mapper/News.php',
  'UthandoNews\Model\News'            => __DIR__ . '/src/UthandoNews/Model/News.php',
  'UthandoNews\Service\News'          => __DIR__ . '/src/UthandoNews/Service/News.php',
);
