<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'UthandoNews\Module'                         => __DIR__ . '/Module.php',
    'UthandoNews\Controller\News'                => __DIR__ . '/src/UthandoNews/Controller/News.php',
    'UthandoNews\Controller\Settings'            => __DIR__ . '/src/UthandoNews/Controller/Settings.php',
    'UthandoNews\Form\News'                      => __DIR__ . '/src/UthandoNews/Form/News.php',
    'UthandoNews\Form\NewsFeedFieldSet'          => __DIR__ . '/src/UthandoNews/Form/NewsFeedFieldSet.php',
    'UthandoNews\Form\NewsOptionsFieldSet'       => __DIR__ . '/src/UthandoNews/Form/NewsOptionsFieldSet.php',
    'UthandoNews\Form\NewsSettings'              => __DIR__ . '/src/UthandoNews/Form/NewsSettings.php',
    'UthandoNews\Hydrator\News'                  => __DIR__ . '/src/UthandoNews/Hydrator/News.php',
    'UthandoNews\InputFilter\News'               => __DIR__ . '/src/UthandoNews/InputFilter/News.php',
    'UthandoNews\Mapper\News'                    => __DIR__ . '/src/UthandoNews/Mapper/News.php',
    'UthandoNews\Model\News'                     => __DIR__ . '/src/UthandoNews/Model/News.php',
    'UthandoNews\Options\FeedOptions'            => __DIR__ . '/src/UthandoNews/Options/FeedOptions.php',
    'UthandoNews\Options\NewsOptions'            => __DIR__ . '/src/UthandoNews/Options/NewsOptions.php',
    'UthandoNews\Service\News'                   => __DIR__ . '/src/UthandoNews/Service/News.php',
    'UthandoNews\Service\NewsFeedOptionsFactory' => __DIR__ . '/src/UthandoNews/Service/NewsFeedOptionsFactory.php',
    'UthandoNews\Service\NewsOptionsFactory'     => __DIR__ . '/src/UthandoNews/Service/NewsOptionsFactory.php',
);
