<?php
// Generated by ZF2's ./bin/templatemap_generator.php
return array(
    'uthando-news/news/add'       => __DIR__ . '/view/uthando-news/news/add.phtml',
    'uthando-news/news/edit'      => __DIR__ . '/view/uthando-news/news/edit.phtml',
    'uthando-news/news/index'     => __DIR__ . '/view/uthando-news/news/index.phtml',
    'uthando-news/news/list'      => __DIR__ . '/view/uthando-news/news/list.phtml',
    'uthando-news/news/news-form' => __DIR__ . '/view/uthando-news/news/news-form.phtml',
    'uthando-news/news/news-item' => __DIR__ . '/view/uthando-news/news/news-item.phtml',
    'uthando-news/news/view'      => __DIR__ . '/view/uthando-news/news/view.phtml',
    'uthando-news/settings/index' => __DIR__ . '/view/uthando-news/settings/index.phtml',
);
