
<?=$this->partial('uthando-admin/partial/search', [
    'name'			=> 'news',
    'searchInputs'	=> [
        'News' => 'title',
    ],
]);?>

<div id="table-news">
    <?=$this->partial('uthando-news/news/list', [
        'models' => $this->models
    ]); ?>
</div>


<script>
    $(document).ready(function(){
        $('#table-news').dataGrid({
            url : 'news/list',
            query: { sort : 'businessListId' },
            searchForm : $('#search-news'),
            paging : 'links',
            columnSort: true
        });
    });
</script>