
<?php
echo $this->headScript()
    ->appendFile($this->themePath('/assets/js/LiveEditor/scripts/innovaeditor.js'))
    ->appendFile($this->themePath('/assets/js/LiveEditor/scripts/jquery.innovaeditor.js'))
    ->appendFile('//ajax.googleapis.com/ajax/libs/webfont/1/webfont.js')
    ->appendFile($this->themePath('/assets/js/LiveEditor/scripts/common/webfont.js'));

$form = $this->form;
$routeArray = array('action' => $this->formAction);
if (isset($this->businessListId)) $routeArray['id'] = $this->businessListId;

if (!$form->get('userId')->getValue()) {
    $userId = $this->identity()->getUserId();
    $form->get('userId')->setValue($userId);
}

?>
<div class="row">
    <form class="col-md-12 form form-horizontal" method="post" action="<?=$this->url('admin/news/edit',
        $routeArray) ?>">
        <fieldset>
            <legend><?=ucwords($this->formAction); ?> Business Form:</legend>
            <div class="row">
                <div class="col-sm-6">
                    <fieldset>
                        <legend>Details</legend>
                        <div class="form-group<?php if ($form->get('title')->getMessages()) echo ' has-error'; ?>">
                            <label class="col-md-4 control-label" for="title"><?=$form->get('title')->getLabel();?></label>
                            <div class="col-md-8">
                                <?=$this->formelement($form->get('title')); ?>
                                <span class="help-block">
                            <?=$this->formElementErrors($form->get('title'), [
                                'class' => 'list-unstyled'
                            ]); ?>
                            </span>
                            </div>
                        </div>
                        <div class="form-group<?php if ($form->get('image')->getMessages()) echo ' has-error'; ?>">
                            <label class="col-md-4 control-label" for="image"><?=$form->get('image')->getLabel();?></label>
                            <div class="col-md-8">
                                <div class="input-group">
                                    <?=$this->formelement($form->get('image')); ?>
                                    <span class="input-group-btn">
                                    <a id="add-news-image-button" class="btn btn-default" data-toggle="modal"
                                       data-target="#news-image-model">
                                        Add Image
                                    </a>
                                </span>
                                </div>
                            <span class="help-block">
                            <?=$this->formElementErrors($form->get('image'), [
                                'class' => 'list-unstyled'
                            ]); ?>
                            </span>
                            </div>
                        </div>
                    </fieldset>
                </div>

                <div class="col-md-6">
                    <fieldset>
                        <legend>HTML Content</legend>
                        <?=$this->formElement($form->get('text')); ?>
                        <div class="<?php if ($form->get('text')->getMessages()) echo ' has-error'; ?>">
                            <span class="help-block">
                                <?=$this->formElementErrors($form->get('text'), [
                                    'class' => 'list-unstyled'
                                ]); ?>
                            </span>
                        </div>
                    </fieldset>
                </div>
            </div>

            <?=$this->formElement($form->get('newsId')); ?>
            <?=$this->formElement($form->get('userId')); ?>
            <?=$this->formElement($form->get('slug')); ?>

            <input type="hidden" name="action" value="<?=$this->formAction; ?>">

            <div class="clearfix">&nbsp;</div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <button type="submit" class="btn btn-primary"
                            data-loading-text="Please wait...">Submit</button>
                    <button type="button" class="btn btn-warning"
                            data-loading-text="Please wait..." onClick="window.location = '<?=$this->url('admin/news', array(
                        'action' => 'list',
                    )) ?>';">Cancel</button>
                </div>
            </div>
        </fieldset>
    </form>
</div>

<div id="news-image-model" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Upload Image</h4>
            </div>
            <div class="modal-body">
                <i class="fa fa-spinner fa-spin"></i>&nbsp;Loading
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button id="news-image-save" type="button" class="btn btn-primary">Upload</button>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">

    $('#news-image-model').on('show.bs.modal', function () {
        $(this).find('.modal-body').load('<?=$this->url('admin/uploader', [
            'action'    => 'upload-form',
        ]);?>');
    });

    $('#news-image-model').on('hide.bs.modal', function (e) {
        $(this).find('.modal-body').html('<i class="fa fa-spinner fa-spin"></i>&nbsp;Loading');

        if (admin.upload && admin.upload.status) {
            $('#news-image').val(admin.upload.image.name);
        }
    });

    $('#news-image-save').on('click', function () {
        $('#upload-form').submit();
    });

    $('#news-content-textarea').liveEdit({
        height: '325px',
        css: [
            'http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css',
            'http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css',
            'http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.css'
        ] /* Apply bootstrap css into the editing area */ ,
        groups: [
            ["group1", "", ["Bold", "Italic", "Underline", "ForeColor", "RemoveFormat"]],
            ["group2", "", ["Bullets", "Numbering", "Indent", "Outdent"]],
            ["group3", "", ["Paragraph", "FontSize", "FontDialog", "TextDialog"]],
            ["group4", "", ["LinkDialog"]],
            ["group5", "", ["Undo", "Redo", "FullScreen", "SourceDialog"]]
        ] /* Toolbar configuration */
    });
    $('#news-content-textarea').data('liveEdit').startedit(); /* Run the Editor */

</script>

