<?php $this->headTitle('Add News') ?>
<?php $this->layout()->pageTitle = $this->translate('Add News');?>

<?php $this->placeholder('header-buttons')->captureStart();?>
<button type="submit" form="form-news" data-toggle="tooltip" title="<?=$this->translate('Save');?>" class="btn btn-primary">
    <i class="fa fa-save"></i>
</button>
<a href="<?=$this->url('admin/news');?>" data-toggle="tooltip" title="<?=$this->translate('Cancel');?>" class="btn btn-default">
    <i class="fa fa-reply"></i>
</a>
<?php $this->placeholder('header-buttons')->captureEnd();?>

<?php

$this->form->setAttributes([
    'method' => 'post',
    'id' => 'form-news',
    'action' => $this->url('admin/news/edit', [
        'action' => 'add',
    ]),
]);

$this->form->get('userId')->setValue($this->identity()->getUserId());

?>

<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title"><i class="fa fa-pencil"></i> <?=$this->translate('Add News');?></h3>
    </div>
    <div class="panel-body">
        <?=$this->form($this->form);?>
    </div>
</div>

<?php $this->textEditor()->summernote();?>
<?php $this->fileManager()->uploadButton('news-image', 'news-image-button');?>
